import { useMemo, useState } from "react";

type GameId = "verse"|"path"|"signal"|"witness"|"protocol"|"wayfinder"|"threads"|"forge";
type Screen = "home"|"games"|"play"|"profile";
type Player = { name:string; avatar:string };
type Challenge = { title:string; instruction:string; items?:string[]; answer?:number; choices?:string[]; truth:string; reflect:string; respond:string };
type Game = { id:GameId; title:string; line:string; description:string; color:string; icon:string; players:string; time:string; challenges:Challenge[] };

const avatars = [
  ["Orange","/avatars/orange.png"],["Watermelon","/avatars/watermelon.png"],["Cherries","/avatars/cherries.png"],["Pillow","/avatars/pillow.png"],["Tent","/avatars/tent.png"],
  ["Kayak","/avatars/kayak.png"],["Pineapple","/avatars/pineapple.png"],["Avocado","/avatars/avocado.png"],["Berry","/avatars/berry.png"],["Red Bean","/avatars/bean.png"]
] as const;

const games:Game[] = [
  {id:"verse",title:"Verse Vault",line:"Think fast. Build truth.",description:"Race your crew to rebuild Scripture before the vault closes.",color:"#ffc928",icon:"book",players:"2–12",time:"8–12 min",challenges:[
    {title:"Rebuild Philippians 4:13",instruction:"Tap the words in the correct order.",items:["I","can","do","all","things","through","Christ","who","strengthens","me"],truth:"Strength comes through Christ, not self-confidence alone.",reflect:"Where do you need Christ’s strength rather than pressure to prove yourself?",respond:"Ask for help in one area this week."},
    {title:"Rebuild Proverbs 3:5",instruction:"Tap the words in the correct order.",items:["Trust","in","the","Lord","with","all","your","heart"],truth:"Faith means trusting God beyond what we can explain.",reflect:"What makes trust difficult when the outcome is unclear?",respond:"Name one decision you will bring to prayer."},
    {title:"Rebuild Matthew 5:14",instruction:"Tap the words in the correct order.",items:["You","are","the","light","of","the","world"],truth:"A faithful life should make hope visible.",reflect:"Where can your choices make hope visible?",respond:"Do one quiet act of encouragement."}
  ]},
  {id:"path",title:"Choose the Way",line:"Your choice shapes the story.",description:"Navigate real-life dilemmas and discover biblical wisdom.",color:"#8fd95a",icon:"path",players:"2–8",time:"12–18 min",challenges:[
    {title:"A new student is mocked in your group chat. What do you do first?",instruction:"Choose the strongest faithful response.",choices:["Message privately and stay silent publicly","Interrupt the pile-on and invite them in","Wait for an adult to notice"],answer:1,truth:"The Good Samaritan chose visible, costly compassion — Luke 10:33–37.",reflect:"Why can public kindness cost more than private sympathy?",respond:"Include one person who is usually overlooked."},
    {title:"You receive credit for work your teammate completed.",instruction:"Choose the strongest faithful response.",choices:["Keep quiet","Share the praise later","Correct the record immediately"],answer:2,truth:"Truthfulness protects character and community — Ephesians 4:25.",reflect:"What makes correcting praise uncomfortable?",respond:"Give accurate credit today."}
  ]},
  {id:"signal",title:"Kingdom Signals",line:"Give clues. Find the connection.",description:"Decode Bible people, places and moments through team clues.",color:"#7cb8ff",icon:"signal",players:"4–16",time:"10–15 min",challenges:[
    {title:"David and Goliath",instruction:"Give clues without using: giant, stone, sling.",truth:"Courage grows when confidence rests in God — 1 Samuel 17.",reflect:"What is the difference between courage and confidence in yourself?",respond:"Take one wise courageous step."},
    {title:"Jesus calms the storm",instruction:"Give clues without using: boat, storm, sleep.",truth:"Jesus is present and authoritative within the storm — Mark 4.",reflect:"What did the disciples discover beyond safer weather?",respond:"Pray together about one pressure."}
  ]},
  {id:"witness",title:"Witness Run",line:"Courage moves quickly.",description:"Complete cooperative missions inspired by faith in action.",color:"#ff8c72",icon:"flame",players:"3–10",time:"10–20 min",challenges:[
    {title:"Welcome mission",instruction:"Name five practical ways to welcome someone who feels invisible.",truth:"I was a stranger and you welcomed me — Matthew 25:35.",reflect:"Which welcome is easiest to promise but hardest to practise?",respond:"Use one idea this week."},
    {title:"Gratitude mission",instruction:"Each player names someone who helped their faith and why.",truth:"Encourage one another and build each other up — 1 Thessalonians 5:11.",reflect:"How did that person help without trying to impress?",respond:"Send a sincere thank-you."}
  ]},
  {id:"protocol",title:"Witness Protocol",line:"Every witness holds a clue.",description:"Share private evidence and reconstruct a Bible event together.",color:"#b9a1ff",icon:"eye",players:"4–30",time:"8–20 min",challenges:[
    {title:"Reconstruct the Good Samaritan",instruction:"Place every witness card in event order.",items:["A traveller is attacked","A priest passes","A Levite passes","A Samaritan stops","The traveller reaches an inn"],truth:"Jesus made the unexpected outsider the model of neighbour-love — Luke 10:25–37.",reflect:"Whose choice changed the direction of the story?",respond:"Name one person your group can include."},
    {title:"Reconstruct Jesus Calms the Storm",instruction:"Place every witness card in event order.",items:["They cross the lake","A violent storm rises","The disciples wake Jesus","Jesus commands the waves","They ask who he is"],truth:"The miracle reveals Jesus’ authority — Mark 4:35–41.",reflect:"What did the question at the end reveal?",respond:"Choose one pressure to pray about."}
  ]},
  {id:"wayfinder",title:"Wayfinder",line:"Listen. Move. Trust the team.",description:"Complete safe missions using different roles and instructions.",color:"#58d7c4",icon:"compass",players:"4–24",time:"10–25 min",challenges:[
    {title:"Peace in the Storm",instruction:"Guide sees the shape. Listener reads the sequence. Builder arranges it. Encourager may request one reset.",truth:"Jesus’ presence changed what the disciples were invited to trust — Mark 4.",reflect:"Whose voice was hardest to hear under pressure?",respond:"Adopt one listening habit."},
    {title:"Many Parts",instruction:"Build a four-part seated rhythm. No player may perform the whole pattern.",truth:"The body needs different parts — 1 Corinthians 12:12–27.",reflect:"Which small contribution proved essential?",respond:"Thank someone often unnoticed."}
  ]},
  {id:"threads",title:"Faith Threads",line:"Find what connects your group.",description:"Share safely, discover common ground and open better conversations.",color:"#f7a9d0",icon:"threads",players:"5–40",time:"10–20 min",challenges:[
    {title:"A small thing that improves a difficult day",instruction:"Write one safe, non-identifying response or skip.",truth:"Encouragement often arrives through ordinary care — 1 Thessalonians 5:11.",reflect:"What shared thread might your group discover?",respond:"Offer one small encouragement."},
    {title:"A time someone helped you feel included",instruction:"Describe the action, not private names or identifying details.",truth:"Christian welcome makes room for others — Romans 15:7.",reflect:"Which welcome could become a group habit?",respond:"Welcome one person before close friends."}
  ]},
  {id:"forge",title:"VerseForge",line:"Build it. Recall it. Live it.",description:"Learn Scripture through context, meaningful clauses and recall.",color:"#ffb454",icon:"hammer",players:"1–30",time:"5–15 min",challenges:[
    {title:"Forge Micah 6:8",instruction:"Arrange the meaningful clauses.",items:["Act justly","love mercy","and walk humbly","with your God"],truth:"Justice, mercy and humility belong together.",reflect:"Which phrase is easiest to admire but hardest to practise?",respond:"Choose one just, merciful or humble action."},
    {title:"Forge Joshua 1:9",instruction:"Arrange the meaningful clauses.",items:["Be strong and courageous","do not be afraid","do not be discouraged","for the Lord your God","will be with you wherever you go"],truth:"Courage rests on God’s presence, not denial of fear.",reflect:"How is courage different from pretending?",respond:"Take one wise step delayed by fear."}
  ]}
];

const iconPaths:Record<string,string>={book:"M4 5h6a3 3 0 0 1 3 3v12a3 3 0 0 0-3-3H4V5Zm16 0h-4a3 3 0 0 0-3 3v12a3 3 0 0 1 3-3h4V5Z",path:"M5 19h4a4 4 0 0 0 4-4v-2a4 4 0 0 1 4-4h2M5 19l3-3M5 19l3 3",signal:"m13 2-8 12h7l-1 8 8-12h-7l1-8Z",flame:"M12 22c4 0 7-3 7-7 0-3-2-5-4-7 0 3-2 4-3 4 1-5-2-8-5-10 1 5-4 7-4 13 0 4 4 7 9 7Z",eye:"M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Zm10 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z",compass:"M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm3-12-2 4-4 2 2-4 4-2Z",threads:"M4 7h5a3 3 0 0 1 3 3v8M20 7h-5a3 3 0 0 0-3 3M7 4 4 7l3 3M17 4l3 3-3 3",hammer:"m14 5 5 5M12 7l5 5M15 2l7 7-3 3-7-7 3-3ZM3 21l9-9"};
function Icon({name,size=24}:{name:string,size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={iconPaths[name]??iconPaths.book}/></svg>}

function loadPlayer():Player|null{try{return JSON.parse(localStorage.getItem("gof-player-v1")||"null")}catch{return null}}

export default function App(){
  const [player,setPlayer]=useState<Player|null>(()=>loadPlayer());
  const [editing,setEditing]=useState(!loadPlayer());
  const [screen,setScreen]=useState<Screen>("home");
  const [selected,setSelected]=useState<GameId>("verse");
  const [level,setLevel]=useState(1); const [score,setScore]=useState(0); const [built,setBuilt]=useState<string[]>([]); const [choice,setChoice]=useState<number|null>(null); const [response,setResponse]=useState(""); const [result,setResult]=useState<"idle"|"right"|"wrong">("idle"); const [sound,setSound]=useState(true);
  const game=games.find(g=>g.id===selected)!; const challenge=useMemo(()=>game.challenges[(level-1)%game.challenges.length],[game,level]);
  const go=(next:Screen)=>{setScreen(next);setResult("idle");setBuilt([]);setChoice(null);setResponse("");scrollTo({top:0,behavior:"smooth"})};
  const openGame=(id:GameId)=>{setSelected(id);setLevel(1);go("play")};
  const savePlayer=(next:Player)=>{localStorage.setItem("gof-player-v1",JSON.stringify(next));setPlayer(next);setEditing(false)};
  return <div className="app">
    <header><button className="brand" onClick={()=>go("home")}><span>✦</span>Games <i>of</i> Faith</button><div className="header-actions"><button className="sound" onClick={()=>setSound(v=>!v)} aria-label="Toggle game sound">{sound?"Sound on":"Sound off"}</button>{player&&<button className="player-chip" onClick={()=>go("profile")}><img src={player.avatar} alt=""/><span>{player.name}</span></button>}</div></header>
    <main>
      {screen==="home"&&<Home player={player} onGame={openGame} onGames={()=>go("games")}/>} 
      {screen==="games"&&<Library onGame={openGame}/>} 
      {screen==="play"&&player&&<Play game={game} player={player} level={level} score={score} challenge={challenge} built={built} choice={choice} response={response} result={result} setBuilt={setBuilt} setChoice={setChoice} setResponse={setResponse} setResult={setResult} onScore={()=>setScore(s=>s+120)} onNext={()=>{setLevel(l=>Math.min(100,l+1));setResult("idle");setBuilt([]);setChoice(null);setResponse("")}} onExit={()=>go("games")}/>} 
      {screen==="profile"&&player&&<Profile player={player} score={score} onEdit={()=>setEditing(true)}/>} 
    </main>
    {screen!=="play"&&<nav><button onClick={()=>go("home")} className={screen==="home"?"active":""}>Home</button><button onClick={()=>go("games")} className={screen==="games"?"active":""}>Games</button><button onClick={()=>go("profile")} className={screen==="profile"?"active":""}>Profile</button></nav>}
    {editing&&<ProfileSetup current={player} onSave={savePlayer}/>} 
  </div>
}

function ProfileSetup({current,onSave}:{current:Player|null;onSave:(p:Player)=>void}){const [name,setName]=useState(current?.name??"");const [avatar,setAvatar]=useState(current?.avatar??"");const clean=name.trim().replace(/\s+/g," ");return <div className="setup-backdrop"><section className="setup" role="dialog" aria-modal="true" aria-labelledby="setup-title"><span className="setup-step">Your player profile</span><h1 id="setup-title">What should your crew call you?</h1><p>Use a first name or nickname. This name and avatar will represent you in every game on this device.</p><label htmlFor="player-name">First name or nickname</label><input id="player-name" value={name} onChange={e=>setName(e.target.value.replace(/[^a-zA-ZÀ-ÿ' -]/g,""))} maxLength={24} placeholder="Enter your player name" autoFocus/><fieldset><legend>Pick your avatar</legend><div className="avatar-grid">{avatars.map(([label,src])=><button type="button" key={src} className={avatar===src?"selected":""} onClick={()=>setAvatar(src)} aria-label={`Choose ${label} avatar`} aria-pressed={avatar===src}><img src={src} alt=""/><span>{label}</span></button>)}</div></fieldset><button className="primary" disabled={clean.length<2||!avatar} onClick={()=>onSave({name:clean,avatar})}>{current?"Save profile":"Start playing"}</button><small>Your profile stays on this device. You can change it from Profile.</small></section></div>}

function Home({player,onGame,onGames}:{player:Player|null;onGame:(id:GameId)=>void;onGames:()=>void}){return <><section className="hero"><div><span className="eyebrow">Multiplayer Bible games</span><h1>{player?`Welcome, ${player.name}.`:"Play together."}<br/><em>Grow in truth.</em></h1><p>Eight meaningful games for friends, families and youth groups—built for movement, conversation, Scripture discovery and response.</p><div className="hero-buttons"><button className="primary" onClick={()=>onGame("protocol")}>Start a game</button><button className="secondary" onClick={onGames}>Explore all games</button></div></div><div className="hero-panel"><div className="hero-avatar">{player&&<img src={player.avatar} alt={`${player.name}'s avatar`}/>}</div><span>READY PLAYER</span><b>{player?.name??"New player"}</b><p>Choose a game and bring your crew together.</p></div></section><section className="section"><div className="section-title"><span>Game library</span><h2>Eight distinct ways to play</h2></div><div className="game-grid">{games.map(g=><GameCard key={g.id} game={g} onClick={()=>onGame(g.id)}/>)}</div></section></>}
function Library({onGame}:{onGame:(id:GameId)=>void}){return <section className="section page"><div className="section-title center"><span>800 structured stages</span><h1>Choose your next game</h1><p>Every game ends with Discover, Reflect and Respond.</p></div><div className="game-grid">{games.map(g=><GameCard key={g.id} game={g} onClick={()=>onGame(g.id)}/>)}</div></section>}
function GameCard({game,onClick}:{game:Game;onClick:()=>void}){return <article className="game-card" style={{"--game":game.color} as React.CSSProperties}><div className="game-art"><Icon name={game.icon} size={38}/><span>100 stages</span></div><div className="game-copy"><small>{game.line}</small><h3>{game.title}</h3><p>{game.description}</p><div className="game-meta"><span>{game.players} players</span><span>{game.time}</span></div><button onClick={onClick}>Play now <b>→</b></button></div></article>}

type PlayProps={game:Game;player:Player;level:number;score:number;challenge:Challenge;built:string[];choice:number|null;response:string;result:"idle"|"right"|"wrong";setBuilt:(v:string[])=>void;setChoice:(v:number)=>void;setResponse:(v:string)=>void;setResult:(v:"idle"|"right"|"wrong")=>void;onScore:()=>void;onNext:()=>void;onExit:()=>void};
function Play(p:PlayProps){const isOrder=!!p.challenge.items;const isChoice=!!p.challenge.choices;const isThread=p.game.id==="threads";const correct=isOrder?p.built.join("|")===p.challenge.items!.join("|"):isChoice?p.choice===p.challenge.answer:true;const ready=isOrder?p.built.length===p.challenge.items!.length:isChoice?p.choice!==null:isThread?p.response.trim().length>=3:true;const submit=()=>{p.setResult(correct?"right":"wrong");if(correct)p.onScore()};return <section className="play" style={{"--game":p.game.color} as React.CSSProperties}><div className="play-top"><button onClick={p.onExit}>×</button><div><span>Stage {p.level} of 100</span><i><b style={{width:`${p.level}%`}}/></i></div><strong>{p.score} points</strong></div><div className="play-grid"><aside><span>Your crew</span><div className="you"><img src={p.player.avatar} alt=""/><div><b>{p.player.name}</b><small>Host player</small></div></div><button>Pause</button><button>Quiet mode</button><button>Extend time</button></aside><article className="challenge"><div className="challenge-icon"><Icon name={p.game.icon} size={34}/></div><span>{p.game.title}</span><h1>{p.challenge.title}</h1><p>{p.challenge.instruction}</p>{isOrder&&<><div className="build-zone">{p.built.length?p.built.map((x,i)=><span key={i}>{x}</span>):<small>Build your answer here</small>}</div><div className="tokens">{[...p.challenge.items!].sort().map((x,i)=><button key={`${x}-${i}`} disabled={p.built.includes(x)} onClick={()=>p.setBuilt([...p.built,x])}>{x}</button>)}</div><button className="clear" onClick={()=>p.setBuilt([])}>Clear</button></>}{isChoice&&<div className="choices">{p.challenge.choices!.map((x,i)=><button key={x} className={p.choice===i?"selected":""} onClick={()=>p.setChoice(i)}><span>{String.fromCharCode(65+i)}</span>{x}</button>)}</div>}{!isOrder&&!isChoice&&!isThread&&<div className="mission">{p.challenge.instruction}</div>}{isThread&&<div className="thread"><textarea value={p.response} onChange={e=>p.setResponse(e.target.value)} maxLength={240} placeholder="Write a safe, non-identifying response…"/><small>Do not include full names, contact details, locations or private information.</small></div>}{p.result==="idle"?<button className="primary full" disabled={!ready} onClick={submit}>{isThread?"Save private response":isOrder?"Check answer":"Complete round"}</button>:<div className={`result ${p.result}`}><h2>{p.result==="right"?"Round complete":"Try that order again"}</h2>{p.result==="right"&&<div className="formation"><div><b>Discover</b><p>{p.challenge.truth}</p></div><div><b>Reflect</b><p>{p.challenge.reflect}</p></div><div><b>Respond</b><p>{p.challenge.respond}</p></div></div>}<button className="primary full" onClick={p.onNext}>Next stage</button></div>}</article><aside className="loop"><span>Formation loop</span><b>Gather</b><b>Play</b><b>Discover</b><b>Reflect</b><b>Respond</b></aside></div></section>}
function Profile({player,score,onEdit}:{player:Player;score:number;onEdit:()=>void}){return <section className="profile page"><div className="profile-head"><img src={player.avatar} alt={`${player.name}'s avatar`}/><div><span>Player profile</span><h1>{player.name}</h1><p>Your chosen identity appears in every Games of Faith room.</p></div><button className="secondary" onClick={onEdit}>Edit player</button></div><div className="stats"><div><b>{score}</b><span>Faith points</span></div><div><b>0</b><span>Stages complete</span></div><div><b>0</b><span>Crew games</span></div></div><div className="privacy"><h2>Profile privacy</h2><p>Your name and avatar are saved on this device. Use a first name or nickname and never enter private contact information.</p></div></section>}
